### ISSUE TITLE
Clever-f conflicts with wordcount function

### ISSUE THREAD

**Issue by eater** [rhysd/clever-f.vim#31] opened 2017-02-22 16:01 UTC
I use this function to keep a live wordcount in the statusline: https://gist.github.com/cormacrelf/d0bee254f5630b0e93c3

When I try to use Clever-f, I get an error
```
Error detected while processing function clever_f#find_with[12]..WordCount:
E523: Not allowed here
```
Is there an easy way to resolve the conflict?

**Comment by rhysd** [comment] 2017-02-23 05:38
Do you know which line causes the error? I could not find the code related to clever-f.vim in your gist.

At least it looks that you should use `normal!` instead of `normal`.

**Comment by eater** [comment] 2017-02-23 21:47
No, I'm not sure where the conflict is! I didn't write the function, I just found the gist. Changing it to `normal!` is a good idea but doesn't fix the error.

Here's a simplified version of the function that still conflicts:

```
function! WordCount()
  if line('$') == 1 && getline(1) == '' 
    return 
  elseif mode() == "i"  || mode() == "n"
    let s:old_status = v:statusmsg
    exe "silent normal! g\<c-g>"
    let b:word_count = str2nr(split(v:statusmsg)[11])
    let v:statusmsg = s:old_status
  endif
  return b:word_count
endfunction
```

**Comment by rhysd** [comment] 2017-02-23 23:18
Thank you for reducing code. But I can still not identify the cause of this bug... Could you show me your status line configuration? I need to reproduce.

**Comment by eater** [comment] 2017-02-25 16:40
From .vimrc:
```
let mystatusline = ""
let mystatusline .= "\ %n\ %*" |                                        " buffer number
let mystatusline .= "\ %<%F%*" |                                        " full path
let mystatusline .= "\ %y%*" |                                          " file type
let mystatusline .= " \%M" |                                            " modified flag
let mystatusline .= "\ %#vimWarn#\%{(&key==\"\"?\"\":\"ENCR\")}%*" |    " encrypted?
let mystatusline .= "\ \[%{v:register}\]" |                             " current register
let mystatusline .= "\ %{getcwd()} "                                   " current working dir
let &statusline = mystatusline
autocmd FileType txt if &statusline !~ "WC: " | setlocal statusline+=\ \ WC:\ %{WordCount()}\ 
```

**Comment by rhysd** [comment] 2017-02-25 16:45
Thanks. I'll try it.

**Comment by rhysd** [comment] 2017-02-25 16:50
I could see the error as below (it seems that it breaks cursor position when entering insert mode, but it looks not related to this issue)

![tmp](https://cloud.githubusercontent.com/assets/823277/23332948/f58efd56-fbc5-11e6-8fe4-816ffbea72c7.gif)

**Comment by eater** [comment] 2017-03-05 18:39
Here's a longer set of error messages. 

```
Error detected while processing function clever_f#find_with[12]..WordCount:
line   11:
E523: Not allowed here
Error detected while processing function clever_f#find_with[12]..WordCount:
line   17:
E684: list index out of range: 11
Error detected while processing function clever_f#find_with[12]..WordCount:
line   17:
E116: Invalid arguments for function str2nr(s:split_wc[11])
Error detected while processing function clever_f#find_with[12]..WordCount:
line   17:
E15: Invalid expression: str2nr(s:split_wc[11])
Error detected while processing function clever_f#find_with[12]..WordCount:
line   11:
E523: Not allowed here
Error detected while processing function clever_f#find_with[12]..WordCount:
line   17:
E684: list index out of range: 11
Error detected while processing function clever_f#find_with[12]..WordCount:
line   17:
E116: Invalid arguments for function str2nr(s:split_wc[11])
Error detected while processing function clever_f#find_with[12]..WordCount:
line   17:
E15: Invalid expression: str2nr(s:split_wc[11])
```

**Comment by chrisbra** [comment] 2017-08-31 11:50
instead of using a selfmade wordcount function, you can use the builtin `wordcount()` function, which has been included in Vim 7.4.1042

**Comment by eater** [comment] 2017-08-31 13:37
Amazing! Thanks, @chrisbra.

**Comment by rhysd** [comment] 2017-08-31 15:52
Thank you @chrisbra. @eater, did it solve this issue?

**Comment by rhysd** [comment] 2017-09-08 06:19
It looks it is a problem of implementation of the function `WordCount()` It seems to be called while clever-f.vim's `f` is used, but not related to this plugin directly. Closing this.

**Closed by rhysd** 2017-09-08 06:19 UTC
